version: '3.1'

services:
  docker-demo2:
    container_name: dockerDemo2
    build: .
    ports:
      - '8010:8009'
    environment:
      MONGO_URI: mongodb://root:example@db:27017/
    # command: >
    #   sh -c "npx prisma db push && npm run start:dev"
    # command: >
    #   sh -c "until npx prisma db push; do echo 'Retrying Prisma...'; sleep 5; done && npm run start:dev"

    depends_on:
      - db

  db:
    image: mongo
    container_name: docker-demo2
    restart: always
    ports:
      - 27018:27017
      # - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
      ME_CONFIG_BASICAUTH: false
volumes:
  mongo-data:
#
#
#
